version: '3.4'

services:
  processor:
    image: ${DOCKER_REGISTRY-}processor
    restart: on-failure
    build:
      context: .
      dockerfile: src/server/Processor/Dockerfile

  clientui:
    image: ${DOCKER_REGISTRY-}clientui
    restart: on-failure
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: src/server/ClientUI/Dockerfile
