version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        retries: 5

  processor:
    image: ${DOCKER_REGISTRY-}processor
    restart: on-failure
    build:
      context: .
      dockerfile: Processor/Dockerfile
    depends_on:
     - rabbitmq

  clientui:
    image: ${DOCKER_REGISTRY-}clientui
    restart: on-failure
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: ClientUI/Dockerfile
    depends_on:
     - rabbitmq

