name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Processor image
      run: docker build . --file "./Processor/Dockerfile" --tag processor:$(date +%s)
    - name: Build Frontend image
      run: docker build . --file "./ClientUI/Dockerfile" --tag clientui:$(date +%s)      
