name: Trigger auto deployment for task-locker-processor

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Processor/**'
    - '.github/workflows/task-locker-frontend-AutoDeployTrigger-564fb4dc-ed63-486f-a64a-33f6940e4a39.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: crtasklocker.azurecr.io
          username: ${{ secrets.TASKLOCKERFRONTEND_REGISTRY_USERNAME }}
          password: ${{ secrets.TASKLOCKERFRONTEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: crtasklocker.azurecr.io/processor:${{ github.sha }}
          file: ./Processor/Dockerfile
          context: .


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TASKLOCKERFRONTEND_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tasklocker-processor -g tasklocker-rg --server crtasklocker.azurecr.io --username  ${{ secrets.TASKLOCKERFRONTEND_REGISTRY_USERNAME }} --password ${{ secrets.TASKLOCKERFRONTEND_REGISTRY_PASSWORD }}
            az containerapp update -n tasklocker-processor -g tasklocker-rg --image crtasklocker.azurecr.io/processor:${{ github.sha }}
